---
- name: "{{ role_name }} | main | Include the OS specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_facts['os_family']|lower }}.yml"

- name: "{{ role_name }} | main | Include Task specific variables"
  ansible.builtin.include_vars:
    file: "{{ task.name }}.yml"
  loop: '{{ vim_tasks }}'
  loop_control:
    loop_var: task
  when: task.enabled

- name: "{{ role_name }} | main | Include enabled tasks"
  ansible.builtin.include_tasks:
    file: "{{ task.name }}.yml"
  loop: '{{ vim_tasks }}'
  loop_control:
    loop_var: task
  when: task.enabled
...
